apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-api
  labels:
    app: dogapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dogapi
  template:
    metadata:
      labels:
        app: dogapi
    spec:
      containers:
        - name: dogapi
          image: thornpar/dogapi:version1
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Development"
          ports:
            - containerPort: 80
    
---

apiVersion: v1
kind: Service
metadata:
  name: dog-api-service
  labels:
    app: dogapi
spec:
  selector:
    app: dogapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  #type: LoadBalancer
  type: ClusterIP
  
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dog-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: demo.rpcode.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: 
              service:
                name: dog-api-service
                port:
                  number: 80
  ingressClassName: nginx