apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-api
  labels:
    app: dogapi
spec:
  replicas: 2
  strategy:
# Note RollingUpdate    
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: dogapi
  template:
    metadata:
      labels:
        app: dogapi
    spec:
      containers:
        - name: dogapi
          image: thornpar/dogapi:version1
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Development"
          ports:
            - containerPort: 80
#NOTE readyness probe
          readinessProbe:
            httpGet:
              path: /api/dogs
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          
        
#while(true); do sleep 0.1; echo $(curl -s http://demo.rpcode.se/api/dogs)|cat; done;
---

apiVersion: v1
kind: Service
metadata:
  name: dog-api-service
  labels:
    app: dogapi
spec:
  selector:
    app: dogapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  #type: LoadBalancer
  type: ClusterIP
  
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dog-api-ingress
spec:
  rules:
    - host: demo.rpcode.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dog-api-service
                port:
                  number: 80
  ingressClassName: nginx


              
              
